parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/osprette.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "willemml/zmk-config"
  dark_mode: auto
  key_w: 100
  key_h: 100
  combo_w: 35
  combo_h: 35
  inner_pad_w: 18
  inner_pad_h: 18
