parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/osprette.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "willemml/zmk-config"
  dark_mode: auto
